# Verify that CodeCortex carries the exact CodeCortex 0.6.2 vendored third_party tree.
if(NOT DEFINED CODECORTEX_SOURCE_DIR)
  message(FATAL_ERROR "CODECORTEX_SOURCE_DIR is required")
endif()
set(_manifest "${CODECORTEX_SOURCE_DIR}/provenance/CODECORTEX_062_THIRD_PARTY_SHA256SUMS.tsv")
if(NOT EXISTS "${_manifest}")
  message(FATAL_ERROR "missing dependency manifest: ${_manifest}")
endif()
file(STRINGS "${_manifest}" _lines)
list(POP_FRONT _lines _header)
set(_checked 0)
foreach(_line IN LISTS _lines)
  if(_line STREQUAL "")
    continue()
  endif()
  string(REPLACE "\t" ";" _parts "${_line}")
  list(LENGTH _parts _n)
  if(NOT _n EQUAL 2)
    message(FATAL_ERROR "invalid dependency manifest row: ${_line}")
  endif()
  list(GET _parts 0 _rel)
  list(GET _parts 1 _expected)
  set(_file "${CODECORTEX_SOURCE_DIR}/third_party/${_rel}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "missing CodeCortex dependency file: third_party/${_rel}")
  endif()
  file(SHA256 "${_file}" _actual)
  if(NOT _actual STREQUAL _expected)
    message(FATAL_ERROR "dependency drift: third_party/${_rel}: expected ${_expected}, got ${_actual}")
  endif()
  math(EXPR _checked "${_checked}+1")
endforeach()
file(GLOB_RECURSE _actual_files RELATIVE "${CODECORTEX_SOURCE_DIR}/third_party" LIST_DIRECTORIES false "${CODECORTEX_SOURCE_DIR}/third_party/*")
list(LENGTH _actual_files _actual_count)
if(NOT _actual_count EQUAL _checked)
  message(FATAL_ERROR "third_party file-count drift: manifest ${_checked}, tree ${_actual_count}")
endif()
message(STATUS "CodeCortex donor dependency verification PASS: ${_checked} third_party files")
